import _type.TtOutLogMethodSection;
import _type.TtOutLogStatus;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import stateLayer.Environment;
import stateLayer.StateX;
import systemLayer.Agent;
import utils.Config;
import utils.Globals;
import utils.OutLog____;
import utils.ProjectPath;
import utils.profiler.SimulationProfiler;

import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;

public class EnvGenerator {

    private static SimulationProfiler profiler = new SimulationProfiler();

    public static void main(String[] args) throws Exception {

        Gson gson = new Gson();

        //============================//============================  Loading Profiler from file
        FileReader prfReader = new FileReader(Config.SimulatingFile);
        profiler = gson.fromJson(prfReader, SimulationProfiler.class);

        if (profiler == null) {
            System.out.println(">> Simulator.init");
            System.out.println("> Error: profiler not found.");
            return;
        }
        profiler.init();

        //============================//============================  Initializing Environment
        Environment environment = new Environment();
        int stateCount = profiler.getStateCountValue();
        int agentsCount = profiler.getAgentsCountValue();
        int pitfallCount = profiler.getPitfallCountValue();
        int simulationRound = profiler.getSimulationRoundValue();

        environment.setIsAutoGenerated(true);
        environment.setAgentsCount(agentsCount);
        environment.setStateCount(stateCount);
        environment.setPitfallCount(pitfallCount);
        environment.setSimulationRound(simulationRound);
        environment.setStates(new ArrayList<>());

        //============================//============================ Creating states
        InitializingStates(environment);

        //============================//============================ Creating Agents
        InitializingAgents(environment);

        //============================ Creating the world and initializing the world and environment

        environment.initForGenerate();

        //============================ Saving environment
        gson = new GsonBuilder()
                .excludeFieldsWithoutExposeAnnotation()
                .create();
        String envJson = gson.toJson(environment);

        int envFileCounter = 0;
        String envFileName = "environment";
        String envFilePath = ProjectPath.instance().environmentDir() + "/" + envFileName;

        File file;

        do {
            envFileCounter++;
            file = new File(envFilePath + "-" + envFileCounter + ".json");
        } while (file.exists() && envFileCounter < 10000);

        try {
            FileWriter writer = new FileWriter(file);
            writer.write(envJson);
            writer.close();
        } catch (IOException ignored) {
        }
    }

    private static void InitializingAgents(Environment environment) {

        int agentsCount = environment.getAgentsCount();

        Agent[] agents = new Agent[agentsCount];

        int id = 0;
        int thisBunchFinished = profiler.getCurrentBunch().getBunchCount();

        for (int i = 0; i < agentsCount; i++) {
            if (i >= thisBunchFinished) {
                thisBunchFinished = thisBunchFinished + profiler.getCurrentBunch().getBunchCount();
            }

            //============================ Creating new state
            agents[i] = new Agent(null, id++);
            agents[i].initForGenerator(profiler);

            //============================  Adding agent to an state
            StateX randomState;
            int tryCount = 0;
            boolean isAddedToState;
            do {
                randomState = environment.getRandomState();
                if (randomState.isIsPitfall()) {
                    isAddedToState = false;
                } else {
                    // checking state capability and adding the agent to it.
                    isAddedToState = randomState.addAgent(agents[i]);
                }
            } while (!isAddedToState && tryCount++ < agentsCount);

            if (isAddedToState) {

                //============================ Adding target states to agent
                agents[i].setState(randomState);

                int targetCounts = agents[i].getTargetCounts();
                StateX prevState = agents[i].getState();
                for (int tc = 0; tc < targetCounts; tc++) {
                    boolean isValidToAddAsTarget;
                    //============================ Adding target state to agents
                    do {
                        randomState = environment.getRandomState();
                        //
                        if (randomState.isIsPitfall()) {
                            isValidToAddAsTarget = false;
                        } else {
                            //-- checking state capability and adding the agent to it.
                            isValidToAddAsTarget = prevState.isAnyPathTo(randomState);
                        }
                        if (isValidToAddAsTarget) {
                            //-- check if added previously as target
                            //isValidToAddAsTarget = !agents[i].isAsTarget(randomState);

                            //-- Check if this target state is equals to previously added target state
                            isValidToAddAsTarget = randomState.getId() != prevState.getId();
                        }
                    } while (!isValidToAddAsTarget && tryCount++ < agentsCount);

                    if (isValidToAddAsTarget) {
                        agents[i].addTarget(randomState);
                        prevState = randomState;
                    }
                }

                System.out.println("world:::init::agent: " + agents[i].getId() + " state: " + agents[i].getState().getId() + " target: " + (agents[i].getCurrentTarget() != null ? agents[i].getCurrentTarget().getId() : "NULL"));
            }
        }
    }

    private static void InitializingStates(Environment environment) throws Exception {

        int stateCount = environment.getStateCount();

        //============================//============================  Creating states
        for (int i = 0; i < stateCount; i++) {
            StateX stateX = new StateX();
            stateX.setId(i);
            stateX.setTargetIds(new ArrayList<>());
            stateX.setCapacity(profiler.getStateCapacityValue());
            environment.getStates().add(stateX);
        }

        //============================ Setting pitfalls
        int pitfallCountValue = environment.getPitfallCount();
        if (pitfallCountValue > 0) {
            int i = 1;
            for (; i <= pitfallCountValue && i < stateCount; ) {
                int stateId = Globals.RANDOM.nextInt(stateCount);
                if (!environment.getStates().get(stateId).isIsPitfall()) {
                    environment.getStates().get(stateId).setIsPitfall(true);
                    environment.getStates().get(stateId).setCapacity(profiler.getAgentsCountValue());
                    i++;
                }
            }
            if (i - 1 != pitfallCountValue) {
                OutLog____.pl(TtOutLogMethodSection.TakeAStepTowardTheTarget, TtOutLogStatus.ERROR, "pitfall count not satisfied. expected pitfalls: " + pitfallCountValue + ". created pitfalls: " + i);
            }
        }

        //============================ Creating target for each state
        for (int i = 0; i < stateCount; i++) {
            StateX stateX = environment.getState(i);

            //-- Continue if this state is a pitfall
            if (stateX.isIsPitfall()) {
                continue;
            }

            int targetCount = profiler.getStateTargetCountValue();

            if (targetCount >= stateCount) {
                OutLog____.pl(TtOutLogMethodSection.Generator_InitializingStates, TtOutLogStatus.ERROR, "Target count (" + targetCount + ") is bigger than state count (" + stateCount + ").");
                throw new Exception("Target count (" + targetCount + ") is bigger than state count (" + stateCount + ").");
            }

            for (int j = 0; j < targetCount; ) {

                int targetId = Globals.RANDOM.nextInt(stateCount);

                //-- ignoring itself as a target
                if (targetId == stateX.getId()) {
                    continue;
                }

                //-- ignoring previously added target to list
                boolean isExist = false;
                for (Integer tId : stateX.getTargetIds()) {
                    if (tId == targetId) {
                        isExist = true;
                        break;
                    }
                }
                if (!isExist) {
                    j++;
                    stateX.getTargetIds().add(targetId);
                }
            }

            //-- Updating target objects of states according their targetIds.
            stateX.updateTargets(environment);
        }


        //-- Sorting agents according less targetsId size
        //-- Used in Main drawing, for best deployment
        environment.getStates().sort((StateX s1, StateX s2) -> {
            ArrayList<Integer> ts1 = s1.getTargetIds();
            ArrayList<Integer> ts2 = s2.getTargetIds();
            if (ts1 == null) {
                return 1;
            }
            if (ts2 == null) {
                return -1;
            }
            if (ts1.size() > ts2.size()) {
                return -1;
            }
            if (ts1.size() < ts2.size()) {
                return 1;
            }
            return 0;
        });
    }
}
